FROM certbot/certbot:latest

RUN apk add --no-cache nginx openssl bash curl gettext

RUN mkdir -p /var/www/certbot /etc/nginx/templates /etc/nginx/ssl

COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY docker/nginx/conf.d/trafficx.conf /etc/nginx/templates/trafficx.conf.template
COPY docker/nginx/entrypoint.sh /entrypoint.sh

EXPOSE 80 443
ENTRYPOINT ["sh", "/entrypoint.sh"]
