packages:
  - "packages/*"
  - "apps/*"
allowBuilds:
  '@morev/vue-transitions': true
  '@openrouter/sdk': true
  '@parcel/watcher': true
  '@prisma/engines': true
  esbuild: true
  maplibre-gl: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  sqlite3: true
  unrs-resolver: true
  vue-demi: true
