allowBuilds:
  '@morev/vue-transitions': true
  '@openrouter/sdk': true
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  maplibre-gl: true
  prisma: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi
onlyBuiltDependencies:
  - '@morev/vue-transitions'
  - '@openrouter/sdk'
  - '@prisma/client'
  - '@prisma/engines'
  - maplibre-gl
  - prisma
  - sharp
