export const STATUS_CONFIG: Record<
  CampaignStatus,
  {
    label: string;
    color: "neutral" | "primary" | "success" | "warning" | "error" | "info";
    icon: string;
  }
> = {
  draft: { label: "Draft", color: "neutral", icon: "i-heroicons-document" },
  queued: { label: "Queued", color: "info", icon: "i-heroicons-clock" },
  running: {
    label: "Running",
    color: "success",
    icon: "i-heroicons-play-circle",
  },
  paused: {
    label: "Paused",
    color: "warning",
    icon: "i-heroicons-pause-circle",
  },
  completed: {
    label: "Completed",
    color: "primary",
    icon: "i-heroicons-check-circle",
  },
  failed: { label: "Failed", color: "error", icon: "i-heroicons-x-circle" },
  cancelled: {
    label: "Cancelled",
    color: "neutral",
    icon: "i-heroicons-stop-circle",
  },
};

export const COUNTRY_LIST = [
  {
    code: "US",
    name: "United States",
    region: "North America",
  },
  { code: "GB", name: "United Kingdom", region: "Europe" },
  { code: "DE", name: "Germany", region: "Europe" },
  { code: "FR", name: "France", region: "Europe" },
  { code: "JP", name: "Japan", region: "Asia" },
  { code: "SG", name: "Singapore", region: "Asia" },
  { code: "ID", name: "Indonesia", region: "Asia" },
  { code: "PH", name: "Philippines", region: "Asia" },
  { code: "VN", name: "Vietnam", region: "Asia" },
  { code: "MY", name: "Malaysia", region: "Asia" },
  { code: "TH", name: "Thailand", region: "Asia" },
  { code: "NG", name: "Nigeria", region: "Africa" },
  { code: "EG", name: "Egypt", region: "Africa" },
  { code: "AR", name: "Argentina", region: "South America" },
  { code: "CL", name: "Chile", region: "South America" },
  { code: "PE", name: "Peru", region: "South America" },
  { code: "CO", name: "Colombia", region: "South America" },
  { code: "VE", name: "Venezuela", region: "South America" },
  { code: "EC", name: "Ecuador", region: "South America" },
  { code: "PY", name: "Paraguay", region: "South America" },
  { code: "UY", name: "Uruguay", region: "South America" },
  { code: "BO", name: "Bolivia", region: "South America" },
  {
    code: "GF",
    name: "French Guiana",
    region: "South America",
  },
  { code: "SR", name: "Suriname", region: "South America" },
  { code: "GY", name: "Guyana", region: "South America" },
  { code: "AU", name: "Australia", region: "Oceania" },
  { code: "NZ", name: "New Zealand", region: "Oceania" },
  { code: "CA", name: "Canada", region: "North America" },
  { code: "BR", name: "Brazil", region: "South America" },
  { code: "MX", name: "Mexico", region: "North America" },
  { code: "RU", name: "Russia", region: "Europe/Asia" },
  { code: "IN", name: "India", region: "Asia" },
  { code: "NL", name: "Netherlands", region: "Europe" },
  { code: "SE", name: "Sweden", region: "Europe" },
  { code: "CH", name: "Switzerland", region: "Europe" },
  { code: "ZA", name: "South Africa", region: "Africa" },
  { code: "KR", name: "South Korea", region: "Asia" },
  { code: "ES", name: "Spain", region: "Europe" },
  { code: "IT", name: "Italy", region: "Europe" },
  { code: "NO", name: "Norway", region: "Europe" },
  { code: "DK", name: "Denmark", region: "Europe" },
  { code: "FI", name: "Finland", region: "Europe" },
  { code: "BE", name: "Belgium", region: "Europe" },
  { code: "AT", name: "Austria", region: "Europe" },
  { code: "IE", name: "Ireland", region: "Europe" },
  { code: "NZ", name: "New Zealand", region: "Oceania" },
  { code: "PL", name: "Poland", region: "Europe" },
  { code: "PT", name: "Portugal", region: "Europe" },
  { code: "GR", name: "Greece", region: "Europe" },
  { code: "HU", name: "Hungary", region: "Europe" },
  { code: "CZ", name: "Czech Republic", region: "Europe" },
  { code: "RO", name: "Romania", region: "Europe" },
  { code: "BG", name: "Bulgaria", region: "Europe" },
  { code: "HR", name: "Croatia", region: "Europe" },
  { code: "SI", name: "Slovenia", region: "Europe" },
  { code: "SK", name: "Slovakia", region: "Europe" },
  { code: "LT", name: "Lithuania", region: "Europe" },
  { code: "LV", name: "Latvia", region: "Europe" },
  { code: "EE", name: "Estonia", region: "Europe" },
];
